// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtp--qfF1EjgHqcIHJ1js6AOT1yRFLU5E',
    appId: '1:596477901843:web:c506ae6b60223d2df2d3e6',
    messagingSenderId: '596477901843',
    projectId: 'rated-001',
    authDomain: 'rated-001.firebaseapp.com',
    databaseURL: 'https://rated-001-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rated-001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcL8wqHc0xso87EUwyEl-Y8X76Yi0bM10',
    appId: '1:596477901843:android:e818542729be8e2af2d3e6',
    messagingSenderId: '596477901843',
    projectId: 'rated-001',
    databaseURL: 'https://rated-001-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rated-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApJr-l_PdAc1mQ705W_FtzLFSmz2a8C_s',
    appId: '1:596477901843:ios:3a4bf351845818daf2d3e6',
    messagingSenderId: '596477901843',
    projectId: 'rated-001',
    databaseURL: 'https://rated-001-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rated-001.appspot.com',
    iosClientId: '596477901843-lk6q5ph2jh4q1tqcbifke45spb81petn.apps.googleusercontent.com',
    iosBundleId: 'com.example.rated',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApJr-l_PdAc1mQ705W_FtzLFSmz2a8C_s',
    appId: '1:596477901843:ios:3a4bf351845818daf2d3e6',
    messagingSenderId: '596477901843',
    projectId: 'rated-001',
    databaseURL: 'https://rated-001-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rated-001.appspot.com',
    iosClientId: '596477901843-lk6q5ph2jh4q1tqcbifke45spb81petn.apps.googleusercontent.com',
    iosBundleId: 'com.example.rated',
  );
}
